steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE}
      - -f
      - services/parser/Dockerfile
      - .
images:
  - ${_IMAGE}
substitutions:
  _IMAGE: parser:latest
options:
  logging: CLOUD_LOGGING_ONLY
